### ISSUE TITLE
reload插件的问题

### ISSUE THREAD

**Issue by j1g5awi** [233a344a455/DeltaBot#3]
我用了您的reload插件，然后使用过程中发现：

由于插件只读取了plugins目录下的文件夹和文件，那么那些被删除的文件不会被读取到。

如果此时我从git上拉取的commit刚好是删除/重命名了一个插件，那么reload之后该插件仍然处在加载状态，甚至会出现同一插件以不同名字加载了很多次的情况。

例如我原先有个插件叫bot_control，我把它重命名为bot_manger。

那么git pull之后该文件夹虽然已经被删除，但是它的原加载仍回在机器人中保留。

于是我们使用usage就会看到两个相同的插件名。

**Comment by deltazefiro** [comment]
感谢您的使用与反馈！

reload插件本身设计仅仅用于调试时方便，并未打算在正常情况下被使用，因此仅仅简单地调用了nonebot的重载函数重载了插件目录下的所有插件

不过我还是会在周末尝试解决这个问题

~~其实我没有想到会有人来测试我这个随手写的项目的 (\*/ω＼\*)，真的十分感谢您的使用与反馈！~~

**Comment by j1g5awi** [comment]
因为我第一次使用cqhttp和nonebot来开发机器人，所以我就搜了一下别人的项目，就发现了您的。

我想到了个解决问题的方法，就是将 `get_loaded_plugins()` 和用 `os.listdir()` 获得的插件名合成一个新的集合，再使用这个集合进行重载就行了，已经被删除的插件自然无法正常重载，也就卸载掉了。

~~其实就是把你注释掉的方法和当前的方法合在一起就行了。~~

**Comment by j1g5awi** [comment]
又出现了个奇怪的问题，在使用了上述方法解决重复加载问题后，当我把bot重命名为bot_control之后，通过bot update命令让挂载在服务器的机器人进行更新后，后台显示bot插件明明加载了却无法对我的指令产生响应。

*bot_update也是用的您的update插件。*

详情可以看我的仓库：[nodice](https://github.com/thereisnodice/nodice)

**Comment by j1g5awi** [comment]
前面发现的问题的解决方法：

无序集的锅，只要改成列表就搞定了。先重载已加载的插件，再加载读取到的插件。

**Comment by deltazefiro** [comment]
再次感谢您提供的解决方案，不过我使用了一种类似的方法也解决了这个问题
我已经在 https://github.com/233a344a455/DeltaBot/commit/52dbee05ed43b00a2f228870933f99338a1b8a88 中将其修复

ps: 其实这也是我第一次开发这种类型的机器人，您的仓库我也star啦，从中学到了不少东西 \~\(≧▽≦)/\~
